theme = "everforest_dark"

[editor]
line-number = "relative"
mouse = false
auto-completion = true
rulers = [
    120,
]
color-modes = true

[editor.cursor-shape]
insert = "underline"
normal = "underline"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = " | "

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

